# Conversion performed at 2026-06-08 10:43:24.538573
dovecot_config_version = %version%
dovecot_storage_version = %version%
compress_gz_level = 6
log_timestamp = "%Y-%m-%d %H:%M:%S "
mail_compress_write_method = gz
mail_plugins = mail_compress
mdbox_rotate_size = 2M
protocols = imap pop3
auth_mechanisms = plain login

namespace inbox {
  inbox = yes
  prefix = INBOX.
  type = private
  mail_driver = maildir
}

# --- GLOBAL SQL BACKEND CONFIGURATION ---
sql_driver = mysql

mysql localhost {
  dbname = panel
  password = %password%
  port = 3306
  user = panel
}

# --- COMPACTED PASSDB & USERDB BLOCKS ---
passdb sql {
  query = SELECT email as user, password FROM email_users WHERE email='%{user}';
}

userdb sql {
  query = SELECT '5000' as uid, '5000' as gid, REPLACE(mail, 'maildir:', '') as home, REPLACE(mail, 'maildir:', '') as mail_path FROM email_users WHERE email='%{user}';
}





# --- SSL & SERVICES ---
ssl = yes
ssl_server {
  cert_file = /etc/dovecot/cert.pem
  key_file = /etc/dovecot/key.pem
}

service auth {
  unix_listener /var/spool/postfix/private/auth {
    mode = 0660
    user = postfix
    group = postfix
  }

  unix_listener auth-master {
    mode = 0600
    user = vmail
  }
}

service auth-worker {
  user = root
}

protocol lda {
  auth_socket_path = /var/run/dovecot/auth-master
  log_path = /home/vmail/dovecot-deliver.log
  postmaster_address = postmaster@vmi2010993.contaboserver.net
}

protocol pop3 {
  pop3_uidl_format = "%{uid | substr(0, 8)}%{uidvalidity | substr(0, 8)}"

  mail_plugins {
    mail_compress = yes
  }
}

protocol imap {
  mail_plugins {
    mail_compress = yes
  }
}

service stats {
  unix_listener stats-reader {
    group = vmail
    mode = 0660
    user = vmail
  }
  unix_listener stats-writer {
    group = vmail
    mode = 0660
    user = vmail
  }
}
